
# practice-service's spring-boot config

# TODO use practice-service in LOGGING_FILE default value

logging:
  file: ${LOGGING_FILE:${spring.application.name}}.log
  path: ${LOGGING_PATH:${user.home}/data/${spring.application.name}/logs}
  level.: ${LOGGING_LEVEL_:INFO}

security:
  user:
    name: ${SECURITY_USER_NAME:admin}
    password: ${SECURITY_USER_PASSWORD:admin_pass}
    role: ADMIN

server:
  port: ${SERVER_PORT:8080}

spring.application.name: practice-service

spring.data.jpa.repositories.enabled: true # Enable JPA repositories.
spring.datasource:
  platform: h2
  maximum-pool-size: 10
  minimum-idle: 5
  name: dataSource
  test-while-idle: true
  time-between-eviction-runs-millis: 1
  validation-query: 'SELECT 1'
  type: 'com.zaxxer.hikari.HikariDataSource'
  driver-class-name: 'org.h2.Driver'
  url: 'jdbc:h2:~/data/practice-service/h2' #'jdbc:h2:mem:practice-service'
  username: sa

spring.h2.console:
  enabled: true
  web-allow-others: true

spring.jpa:
  database: H2 # Target database to operate on, auto-detected by default. Can be alternatively set using the "databasePlatform" property.
  database-platform: 'org.hibernate.dialect.H2Dialect' # Name of the target database to operate on, auto-detected by default. Can be alternatively set using the "Database" enum.
  generate-ddl: true # Initialize the schema on startup.
  hibernate.ddl-auto: none # DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property. Default to "create-drop" when using an embedded database, "none" otherwise.
  hibernate.naming-strategy: 'org.hibernate.cfg.ImprovedNamingStrategy' # Naming strategy fully qualified name.
  #hibernate.naming-strategy: 'spring.jpa.hibernate.naming_strategy=org.hibernate.cfg.EJB3NamingStrategy' # uppercase name
  show-sql: true # Enable logging of SQL statements.

---
spring:
  profiles: development.env

---
spring:
  profiles: it.env

spring.datasource:
  url: 'jdbc:h2:mem:micro-service'

---
spring:
  profiles: staging.env

---
spring:
  profiles: production.env

spring.jpa:
  generate-ddl: false
